version: '3'
services:
  db:
    container_name: portfolio_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: dev_internal_user
      MYSQL_PASSWORD: dev_password
    networks:
      - network 
  portfolio_api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    container_name: portfolio_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://dev_internal_user:dev_password@db:3306/portfolio_db
      SERVER_PORT: 8080
      SERVER_HOST: 0.0.0.0
      JWT_KEY_PATH: .jwt.private.key
      JWT_EXPIRATION_IN_HOURS: 2
    networks:
      - network 

networks:
  network:
