version: '3'
services:
  api:
    container_name: portfolio_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://dev_internal_user:dev_password@localhost:3306/portfolio_db
    env_file:
      - .env
  database:
    container_name: portfolio_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: dev_internal_user 
      POSTGRES_PASSWORD: dev_password 

