CREATE TABLE blogs (
  id INT NOT NULL AUTO_INCREMENT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
  title VARCHAR(256) UNIQUE NOT NULL,
  summary TEXT NOT NULL,
  body MEDIUMTEXT NOT NULL,
  visible BOOLEAN NOT NULL DEFAULT TRUE,

  PRIMARY KEY (id)
);